# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hakkinda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hakkinda(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(804, 656)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setStyleSheet("\n"
"background-color: rgb(226, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"    border-color: #051a39;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 601, 301))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 320, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 210, 191, 121))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 360, 731, 211))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 580, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(490, 580, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hakkında"))
        self.label_2.setText(_translate("Dialog", "  GÜVEN HUKUK"))
        self.label_3.setText(_translate("Dialog", "𝓓𝓮𝓿𝓵𝓮𝓽𝓵𝓮𝓻𝓲𝓷 \n"
" 𝓻𝓮𝓯𝓪𝓱ı 𝓹𝓪𝓻𝓪𝔂𝓵𝓪  \n"
"𝓭𝓮𝓰̆𝓲𝓵 𝓪𝓭𝓪𝓵𝓮𝓽𝓵𝓮 \n"
" 𝓸̈𝓵𝓬̧𝓾̈𝓵𝓾̈𝓻.\n"
"       𝓚𝓞𝓝𝓕𝓤̈𝓒𝓨𝓤̈𝓢\n"
""))
        self.label_4.setText(_translate("Dialog", "   Güven Hukuk Bürosu müvekkilleri için sağladığı hukuki hizmetlerinde özellikle eşitlik, dürüstlük, \n"
" güven, saygı ve nezaket çerçevesinde davranarak avukatlık mesleğinin gerektirdiği hukuksal \n"
" faaliyetleri yerine getirme gayreti içerisindedir. Gelişme ve istikrarı kendisine amaç edinen ve \n"
" alanında en iyisi olma amacıyla çalışan avukatlardan oluşan Örnek Hukuk Bürosu hep daha \n"
" iyisine ulaşmayı hedef haline getirenlerin başvuracağı bir hukuk bürosudur.\n"
"\n"
"Alanında \n"
" uzman avukatlar, akademik danışmanlar ve ilgili departmanlarımızın diğer idari personelleri \n"
" ile yürüttüğümüz çalışmalarımızı inceleyerek sözlü ve yazılı danışmanlık almak ve tarafı \n"
" olduğunuz her türlü uyuşmazlıkta tarafınızı temsil etmemiz için aşağıda yer alan \n"
" bağlantı yolları ile tarafımızla iletişime geçebilirsiniz."))
        self.label_5.setText(_translate("Dialog", "E-Mail: info@guvenhukuk.com \n"
"📞:0 216 564 84 56"))
        self.label_6.setText(_translate("Dialog", "Adres: Fevzi Çakmak cd. 3.Sok. \n"
"No:9/4 Bahçelievler-İstanbul "))
