# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sifreleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sifreleme(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 561)
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(226, 255, 255);\n"
"    border-color: #051a39;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 461, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 260, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(57, 200, 186);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(150, 320, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(57, 200, 186);\n"
"color: rgb(0, 0, 0);")
        self.groupBox.setObjectName("groupBox")
        self.lne_sifregir = QtWidgets.QLineEdit(self.groupBox)
        self.lne_sifregir.setGeometry(QtCore.QRect(20, 40, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lne_sifregir.setFont(font)
        self.lne_sifregir.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_sifregir.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lne_sifregir.setObjectName("lne_sifregir")
        self.btn_cancel = QtWidgets.QPushButton(self.groupBox)
        self.btn_cancel.setGeometry(QtCore.QRect(20, 90, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_ok = QtWidgets.QPushButton(self.groupBox)
        self.btn_ok.setGeometry(QtCore.QRect(130, 90, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok.setFont(font)
        self.btn_ok.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.btn_ok.setObjectName("btn_ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Şifreleme"))
        self.label_2.setText(_translate("MainWindow", "𝓗𝓤𝓚𝓤𝓚 𝓑𝓤̈𝓡𝓞𝓢𝓤 𝓣𝓐𝓚𝓘̇𝓟 𝓟𝓡𝓞𝓖𝓡𝓐𝓜𝓘"))
        self.groupBox.setTitle(_translate("MainWindow", "Şifre Giriniz"))
        self.btn_cancel.setText(_translate("MainWindow", "CANCEL"))
        self.btn_ok.setText(_translate("MainWindow", "OK"))
