# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hukuk1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_Hukuk1(object):
    def setupUi(self, mw_Hukuk1):
        mw_Hukuk1.setObjectName("mw_Hukuk1")
        mw_Hukuk1.resize(1302, 870)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        mw_Hukuk1.setFont(font)
        mw_Hukuk1.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"background-color: rgb(212, 248, 255);\n"
"background-color: rgb(170, 170, 255);\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
"SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #e2ffff;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar\n"
"{\n"
"    background-color: #484c58;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #898988;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #c4c5c3;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background-color: #979796;\n"
"    border: 1px solid #000;\n"
"    margin-bottom: -1px;\n"
"    padding-bottom: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #c4c5c3;\n"
"    border: 1px solid;\n"
"    color: #000000;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 1px;\n"
"    background-color: #363942;\n"
"    color: #ffffff;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    min-width : 150px;\n"
"    padding: 3px 20px 3px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #363942;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #898988;\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    background-color: #bbbcba;\n"
"    color: #000000;\n"
"    border-color: #051a39;\n"
"    border : 1px solid #000000;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:0.486, y1:0, x2:0.505, y2:1, stop:0.00480769 rgba(170, 0, 0, 255),stop:1 rgba(122, 0, 0, 255));\n"
"    color: rgb(0, 0, 0);\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #9c0000;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #880000;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 3px;\n"
"    border-color: #000000;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(177, 181, 193, 255),stop:1 rgba(159, 163, 174, 255));\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: #9fa3ae;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: #7b7e86;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 3px;\n"
"    border-color: #000000;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(118, 118, 118, 255),stop:1 rgba(70, 70, 70, 255));\n"
"    border: 1px solid #333333;\n"
"    border-radius: 3px;\n"
"    padding-left: 6px;\n"
"    color:#000000;\n"
"    font-weight: bold;\n"
"    height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: #646464;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #979796;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #c4c5c3;\n"
"    color: #000000;\n"
"    border: 1px solid black;\n"
"    selection-background-color: #363942;\n"
"    selection-color: #ffffff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; \n"
"    border-top-right-radius: 3px; \n"
"    border-bottom-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"\n"
"\n"
"/*-----QSpinBox & QDoubleSpinBox & QDateTimeEdit-----*/\n"
"QSpinBox, \n"
"QDoubleSpinBox,\n"
"QDateTimeEdit\n"
"{\n"
"    background-color: #000000;\n"
"    color: #00ff00;\n"
"    font-weight: bold;\n"
"    border: 1px solid #333333;\n"
"    padding : 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox:hover, \n"
"QDoubleSpinBox::hover,\n"
"QDateTimeEdit::hover\n"
"{\n"
"    border: 1px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(118, 118, 118, 255),stop:1 rgba(70, 70, 70, 255));\n"
"    border: 0px solid #333333;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover\n"
"{\n"
"    background-color: #646464;\n"
"    border: 1px solid #333333;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:disabled, QSpinBox::down-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled, QDoubleSpinBox::down-button:disabled,\n"
"QDateTimeEdit::up-button:disabled, QDateTimeEdit::down-button:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed,\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button::pressed,\n"
"QDateTimeEdit::up-button:pressed, QDateTimeEdit::down-button::pressed\n"
"{\n"
"    background-color: #979796;\n"
"    border: 1px solid #444444;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow,\n"
"QDoubleSpinBox::down-arrow,\n"
"QDateTimeEdit::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow,\n"
"QDoubleSpinBox::up-arrow,\n"
"QDateTimeEdit::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #000000;\n"
"    color:rgb(0, 0, 0);\n"
"    font-weight: bold;\n"
"    border: 1px solid #333333;\n"
"    padding: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"    border: 1px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 1px;\n"
"    border-color: #051a39;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTextEdit-----*/\n"
"QTextEdit\n"
"{\n"
"    background-color: #808080;\n"
"    color:rgb(0, 0, 0);\n"
"    border: 1px groove #333333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTextEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px groove #333333;\n"
"    border-radius: 2px;\n"
"    margin-top: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:0.486, y1:0, x2:0.505, y2:1, stop:0.00480769 rgba(170, 169, 169, 255),stop:1 rgba(122, 122, 122, 255));\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: #50aae5;\n"
"    color: #000000;\n"
"    border: 2px groove #333333;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox{\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 2px solid #222222;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(://checkbox.png);\n"
"    border: 2px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 2px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton{\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked\n"
"{ \n"
"    border: 2px inset #1e8bff; \n"
"    border-radius: 6px; \n"
"    background-color:  #323232;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover\n"
"{ \n"
"    border: 2px solid #ffffff; \n"
"    border-radius: 5px; \n"
"    background-color:  #323232;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked\n"
"{ \n"
"    border: 2px inset #1e8bff; \n"
"    border-radius: 5px; \n"
"    background-color: #rgb(56, 219, 255); \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 2px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"QTableView\n"
"{\n"
"    background-color: #808080;\n"
"    border: 1px groove #333333;\n"
"    color: #f0f0f0;\n"
"    font-weight: bold;\n"
"    gridline-color: #333333;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::disabled\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #656565;\n"
"    gridline-color: #656565;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:hover \n"
"{\n"
"    background-color: #484c58;\n"
"    color: #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected \n"
"{\n"
"    background-color: #484c58;\n"
"    border: 2px groove #00ff00;\n"
"    color: #F0F0F0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #282830;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #282830;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"{\n"
"    color: #656565;\n"
"    background-color: #525251;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabWidget-----*/\n"
"QTabBar::tab\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    width: 80px;\n"
"    height: 9px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QTabBar::tab:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    border: 1px groove #333333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: #484c58;\n"
"    color: #ffffff;\n"
"    border: 1px groove #333333;\n"
"    border-bottom: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected \n"
"{\n"
"    background-color: #a3a7b2;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    background-color: #484c58;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:!selected \n"
"{\n"
"    margin-top: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:!selected \n"
"{\n"
"    margin-bottom: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom \n"
"{\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:selected \n"
"{\n"
"    border-bottom-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:selected \n"
"{\n"
"    border-top-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
"{\n"
"    margin-right: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:!selected \n"
"{\n"
"    margin-right: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    margin-left: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right \n"
"{\n"
"    min-height: 15ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:selected \n"
"{\n"
"    border-left-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:selected \n"
"{\n"
"    border-right-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
"{\n"
"    margin-bottom: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSlider-----*/\n"
"QSlider{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:1, y2:1, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000; \n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:1, y2:1, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000; \n"
"    width: 12px;\n"
"    margin-top: -6px;\n"
"    margin-bottom: -6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: #808080;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:vertical \n"
"{\n"
"    background-color: transparent;\n"
"    width: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0.483, x2:1, y2:0.517, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0.483, x2:1, y2:0.517, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000;\n"
"    height: 12px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:hover \n"
"{\n"
"    background-color: #808080;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDial-----*/\n"
"QDial\n"
"{\n"
"    background-color: #600000;\n"
"\n"
"}\n"
"\n"
"\n"
"QDial::disabled\n"
"{\n"
"    background-color: #404040;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #63676d;\n"
"    height: 18px;\n"
"    margin: 0px 18px 0 18px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: #a6acb3;\n"
"    border: 1px solid #656565;\n"
"    border-radius: 2px;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    width: 18px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    width: 18px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-right.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-left.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #63676d;\n"
"    width: 18px;\n"
"    margin: 18px 0 18px 0;\n"
"    border: 1px solid #222222;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #a6acb3;\n"
"    border: 1px solid #656565;\n"
"    border-radius: 2px;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    height: 18px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    height: 18px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    background-color: #000;\n"
"    color: #00ff00;\n"
"    font-weight: bold;\n"
"    border: 0px groove #000;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"    border: 1px solid #000;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #ffaf02;\n"
"    border: 0px;\n"
"    border-radius: 10px;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"    background-color: #333;\n"
"    border: 0px;\n"
"    border-radius: 10px;\n"
"    color: #656565;\n"
"}\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"QStatusBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(102, 115, 140, 255),stop:1 rgba(56, 63, 77, 255));\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(mw_Hukuk1)
        self.centralwidget.setObjectName("centralwidget")
        self.tblw_Liste = QtWidgets.QTableWidget(self.centralwidget)
        self.tblw_Liste.setGeometry(QtCore.QRect(-10, 510, 1301, 331))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.tblw_Liste.setFont(font)
        self.tblw_Liste.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.045, x2:0, y2:0, stop:0 rgba(127, 231, 169, 255), stop:0.427861 rgba(107, 235, 199, 255), stop:0.915423 rgba(99, 210, 227, 255));")
        self.tblw_Liste.setObjectName("tblw_Liste")
        self.tblw_Liste.setColumnCount(18)
        self.tblw_Liste.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblw_Liste.setHorizontalHeaderItem(17, item)
        self.tblw_Liste.horizontalHeader().setDefaultSectionSize(130)
        self.tblw_Liste.horizontalHeader().setMinimumSectionSize(53)
        self.btn_KayitEkle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_KayitEkle.setGeometry(QtCore.QRect(410, 320, 141, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_KayitEkle.setFont(font)
        self.btn_KayitEkle.setStyleSheet("\n"
"background-color: rgb(59, 174, 236);")
        self.btn_KayitEkle.setObjectName("btn_KayitEkle")
        self.btn_KayitGuncelle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_KayitGuncelle.setGeometry(QtCore.QRect(410, 420, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_KayitGuncelle.setFont(font)
        self.btn_KayitGuncelle.setStyleSheet("background-color: rgb(59, 174, 236);")
        self.btn_KayitGuncelle.setObjectName("btn_KayitGuncelle")
        self.btn_KayitSil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_KayitSil.setGeometry(QtCore.QRect(410, 370, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_KayitSil.setFont(font)
        self.btn_KayitSil.setStyleSheet("background-color: rgb(59, 174, 236);")
        self.btn_KayitSil.setObjectName("btn_KayitSil")
        self.grb_DavaciBilgileri = QtWidgets.QGroupBox(self.centralwidget)
        self.grb_DavaciBilgileri.setGeometry(QtCore.QRect(110, 10, 281, 441))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.grb_DavaciBilgileri.setFont(font)
        self.grb_DavaciBilgileri.setStyleSheet("background-color: rgb(57, 200, 186);")
        self.grb_DavaciBilgileri.setObjectName("grb_DavaciBilgileri")
        self.rbtn_Bekar = QtWidgets.QRadioButton(self.grb_DavaciBilgileri)
        self.rbtn_Bekar.setGeometry(QtCore.QRect(210, 160, 61, 20))
        self.rbtn_Bekar.setObjectName("rbtn_Bekar")
        self.label_4 = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_4.setObjectName("label_4")
        self.lne_MuvekkilAdSoyad = QtWidgets.QLineEdit(self.grb_DavaciBilgileri)
        self.lne_MuvekkilAdSoyad.setGeometry(QtCore.QRect(150, 40, 113, 22))
        self.lne_MuvekkilAdSoyad.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_MuvekkilAdSoyad.setObjectName("lne_MuvekkilAdSoyad")
        self.lne_MuvekilCepNo = QtWidgets.QLineEdit(self.grb_DavaciBilgileri)
        self.lne_MuvekilCepNo.setGeometry(QtCore.QRect(150, 120, 113, 21))
        self.lne_MuvekilCepNo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_MuvekilCepNo.setObjectName("lne_MuvekilCepNo")
        self.rbtn_Evli = QtWidgets.QRadioButton(self.grb_DavaciBilgileri)
        self.rbtn_Evli.setGeometry(QtCore.QRect(150, 160, 51, 20))
        self.rbtn_Evli.setObjectName("rbtn_Evli")
        self.lne_DavaAvukati = QtWidgets.QLineEdit(self.grb_DavaciBilgileri)
        self.lne_DavaAvukati.setGeometry(QtCore.QRect(150, 350, 113, 22))
        self.lne_DavaAvukati.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_DavaAvukati.setObjectName("lne_DavaAvukati")
        self.label_5 = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_3.setObjectName("label_3")
        self.cmb_ilce = QtWidgets.QComboBox(self.grb_DavaciBilgileri)
        self.cmb_ilce.setGeometry(QtCore.QRect(150, 200, 111, 22))
        self.cmb_ilce.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_ilce.setObjectName("cmb_ilce")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.cmb_ilce.addItem("")
        self.txt_MuvekkilAdresi = QtWidgets.QTextEdit(self.grb_DavaciBilgileri)
        self.txt_MuvekkilAdresi.setGeometry(QtCore.QRect(150, 240, 121, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_MuvekkilAdresi.setFont(font)
        self.txt_MuvekkilAdresi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_MuvekkilAdresi.setObjectName("txt_MuvekkilAdresi")
        self.lne_MuvekkilTCNo = QtWidgets.QLineEdit(self.grb_DavaciBilgileri)
        self.lne_MuvekkilTCNo.setGeometry(QtCore.QRect(150, 80, 113, 22))
        self.lne_MuvekkilTCNo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_MuvekkilTCNo.setMaxLength(11)
        self.lne_MuvekkilTCNo.setObjectName("lne_MuvekkilTCNo")
        self.label_17 = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label_17.setGeometry(QtCore.QRect(10, 200, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_17.setObjectName("label_17")
        self.label = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label.setGeometry(QtCore.QRect(10, 40, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(228, 255, 241);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label.setObjectName("label")
        self.label_13 = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label_13.setGeometry(QtCore.QRect(10, 350, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(self.grb_DavaciBilgileri)
        self.label_19.setGeometry(QtCore.QRect(10, 390, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(228, 255, 241);\n"
"")
        self.label_19.setObjectName("label_19")
        self.spnb_ucret = QtWidgets.QSpinBox(self.grb_DavaciBilgileri)
        self.spnb_ucret.setGeometry(QtCore.QRect(150, 390, 111, 22))
        self.spnb_ucret.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.spnb_ucret.setPrefix("")
        self.spnb_ucret.setMinimum(8000)
        self.spnb_ucret.setMaximum(67000)
        self.spnb_ucret.setSingleStep(1000)
        self.spnb_ucret.setProperty("value", 8000)
        self.spnb_ucret.setObjectName("spnb_ucret")
        self.grb_DavaliBilgileri = QtWidgets.QGroupBox(self.centralwidget)
        self.grb_DavaliBilgileri.setGeometry(QtCore.QRect(410, 10, 311, 291))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.grb_DavaliBilgileri.setFont(font)
        self.grb_DavaliBilgileri.setStyleSheet("background-color: rgb(57, 200, 186);")
        self.grb_DavaliBilgileri.setObjectName("grb_DavaliBilgileri")
        self.label_14 = QtWidgets.QLabel(self.grb_DavaliBilgileri)
        self.label_14.setGeometry(QtCore.QRect(10, 120, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.grb_DavaliBilgileri)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.grb_DavaliBilgileri)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.grb_DavaliBilgileri)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_10.setObjectName("label_10")
        self.lne_DavaliCepNo = QtWidgets.QLineEdit(self.grb_DavaliBilgileri)
        self.lne_DavaliCepNo.setGeometry(QtCore.QRect(160, 80, 113, 22))
        self.lne_DavaliCepNo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_DavaliCepNo.setObjectName("lne_DavaliCepNo")
        self.txt_DavaliAdresi = QtWidgets.QTextEdit(self.grb_DavaliBilgileri)
        self.txt_DavaliAdresi.setGeometry(QtCore.QRect(160, 160, 121, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_DavaliAdresi.setFont(font)
        self.txt_DavaliAdresi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_DavaliAdresi.setObjectName("txt_DavaliAdresi")
        self.lne_DavaliAdSoyad = QtWidgets.QLineEdit(self.grb_DavaliBilgileri)
        self.lne_DavaliAdSoyad.setGeometry(QtCore.QRect(160, 40, 113, 22))
        self.lne_DavaliAdSoyad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_DavaliAdSoyad.setObjectName("lne_DavaliAdSoyad")
        self.lne_KarsiAvukat = QtWidgets.QLineEdit(self.grb_DavaliBilgileri)
        self.lne_KarsiAvukat.setGeometry(QtCore.QRect(160, 120, 113, 21))
        self.lne_KarsiAvukat.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_KarsiAvukat.setObjectName("lne_KarsiAvukat")
        self.grb_DavaBilgileri = QtWidgets.QGroupBox(self.centralwidget)
        self.grb_DavaBilgileri.setGeometry(QtCore.QRect(750, 10, 531, 441))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.grb_DavaBilgileri.setFont(font)
        self.grb_DavaBilgileri.setStyleSheet("background-color: rgb(57, 200, 186);")
        self.grb_DavaBilgileri.setObjectName("grb_DavaBilgileri")
        self.cmb_DurusmaSalonu = QtWidgets.QComboBox(self.grb_DavaBilgileri)
        self.cmb_DurusmaSalonu.setGeometry(QtCore.QRect(160, 120, 171, 22))
        self.cmb_DurusmaSalonu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_DurusmaSalonu.setObjectName("cmb_DurusmaSalonu")
        self.cmb_DurusmaSalonu.addItem("")
        self.cmb_DurusmaSalonu.addItem("")
        self.cmb_DurusmaSalonu.addItem("")
        self.cmb_DurusmaSalonu.addItem("")
        self.cmb_DurusmaSalonu.addItem("")
        self.cmb_DurusmaSalonu.addItem("")
        self.cmb_DurusmaSalonu.addItem("")
        self.cmb_MahkemeBinasi = QtWidgets.QComboBox(self.grb_DavaBilgileri)
        self.cmb_MahkemeBinasi.setGeometry(QtCore.QRect(160, 90, 171, 22))
        self.cmb_MahkemeBinasi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_MahkemeBinasi.setObjectName("cmb_MahkemeBinasi")
        self.cmb_MahkemeBinasi.addItem("")
        self.cmb_MahkemeBinasi.addItem("")
        self.cmb_MahkemeBinasi.addItem("")
        self.cmb_MahkemeBinasi.addItem("")
        self.cmb_MahkemeBinasi.addItem("")
        self.cmb_MahkemeBinasi.addItem("")
        self.label_7 = QtWidgets.QLabel(self.grb_DavaBilgileri)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.grb_DavaBilgileri)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_6.setObjectName("label_6")
        self.rbtn_Yok = QtWidgets.QRadioButton(self.grb_DavaBilgileri)
        self.rbtn_Yok.setGeometry(QtCore.QRect(250, 60, 51, 20))
        self.rbtn_Yok.setObjectName("rbtn_Yok")
        self.rbtn_Var = QtWidgets.QRadioButton(self.grb_DavaBilgileri)
        self.rbtn_Var.setGeometry(QtCore.QRect(170, 60, 51, 20))
        self.rbtn_Var.setObjectName("rbtn_Var")
        self.cmb_DavaTuru = QtWidgets.QComboBox(self.grb_DavaBilgileri)
        self.cmb_DavaTuru.setGeometry(QtCore.QRect(160, 30, 171, 22))
        self.cmb_DavaTuru.setToolTipDuration(-4)
        self.cmb_DavaTuru.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_DavaTuru.setCurrentText("")
        self.cmb_DavaTuru.setObjectName("cmb_DavaTuru")
        self.cmb_DavaTuru.addItem("")
        self.cmb_DavaTuru.addItem("")
        self.cmb_DavaTuru.addItem("")
        self.cmb_DavaTuru.addItem("")
        self.label_16 = QtWidgets.QLabel(self.grb_DavaBilgileri)
        self.label_16.setGeometry(QtCore.QRect(10, 90, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.grb_DavaBilgileri)
        self.label_18.setGeometry(QtCore.QRect(10, 120, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("\n"
"background-color: rgb(228, 255, 241);")
        self.label_18.setObjectName("label_18")
        self.clw_DurusmaTarihi = QtWidgets.QCalendarWidget(self.grb_DavaBilgileri)
        self.clw_DurusmaTarihi.setGeometry(QtCore.QRect(140, 160, 392, 241))
        self.clw_DurusmaTarihi.setStyleSheet("color: rgb(0, 0, 0);")
        self.clw_DurusmaTarihi.setObjectName("clw_DurusmaTarihi")
        self.label_15 = QtWidgets.QLabel(self.grb_DavaBilgileri)
        self.label_15.setGeometry(QtCore.QRect(10, 160, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(228, 255, 241);")
        self.label_15.setObjectName("label_15")
        self.btn_Listele = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Listele.setGeometry(QtCore.QRect(580, 370, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Listele.setFont(font)
        self.btn_Listele.setStyleSheet("background-color: rgb(59, 174, 236);")
        self.btn_Listele.setObjectName("btn_Listele")
        self.btn_KayitAra = QtWidgets.QPushButton(self.centralwidget)
        self.btn_KayitAra.setGeometry(QtCore.QRect(580, 320, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_KayitAra.setFont(font)
        self.btn_KayitAra.setStyleSheet("background-color: rgb(59, 174, 236);")
        self.btn_KayitAra.setObjectName("btn_KayitAra")
        self.btn_Cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cikis.setGeometry(QtCore.QRect(580, 420, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Cikis.setFont(font)
        self.btn_Cikis.setStyleSheet("\n"
"background-color: rgb(36, 79, 220);")
        self.btn_Cikis.setObjectName("btn_Cikis")
        self.btn_hakkinda = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hakkinda.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.btn_hakkinda.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(36, 79, 220);")
        self.btn_hakkinda.setObjectName("btn_hakkinda")
        mw_Hukuk1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mw_Hukuk1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 26))
        self.menubar.setObjectName("menubar")
        mw_Hukuk1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mw_Hukuk1)
        self.statusbar.setObjectName("statusbar")
        mw_Hukuk1.setStatusBar(self.statusbar)
        self.actionHakk_nda = QtWidgets.QAction(mw_Hukuk1)
        self.actionHakk_nda.setObjectName("actionHakk_nda")

        self.retranslateUi(mw_Hukuk1)
        self.cmb_ilce.setCurrentIndex(-1)
        self.cmb_DurusmaSalonu.setCurrentIndex(-1)
        self.cmb_MahkemeBinasi.setCurrentIndex(-1)
        self.cmb_DavaTuru.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(mw_Hukuk1)

    def retranslateUi(self, mw_Hukuk1):
        _translate = QtCore.QCoreApplication.translate
        mw_Hukuk1.setWindowTitle(_translate("mw_Hukuk1", "Hukuk Bürosu Takip Programı"))
        item = self.tblw_Liste.verticalHeaderItem(0)
        item.setText(_translate("mw_Hukuk1", "1"))
        item = self.tblw_Liste.verticalHeaderItem(1)
        item.setText(_translate("mw_Hukuk1", "2"))
        item = self.tblw_Liste.verticalHeaderItem(2)
        item.setText(_translate("mw_Hukuk1", "3"))
        item = self.tblw_Liste.verticalHeaderItem(3)
        item.setText(_translate("mw_Hukuk1", "4"))
        item = self.tblw_Liste.verticalHeaderItem(4)
        item.setText(_translate("mw_Hukuk1", "5"))
        item = self.tblw_Liste.verticalHeaderItem(5)
        item.setText(_translate("mw_Hukuk1", "6"))
        item = self.tblw_Liste.verticalHeaderItem(6)
        item.setText(_translate("mw_Hukuk1", "7"))
        item = self.tblw_Liste.verticalHeaderItem(7)
        item.setText(_translate("mw_Hukuk1", "8"))
        item = self.tblw_Liste.verticalHeaderItem(8)
        item.setText(_translate("mw_Hukuk1", "9"))
        item = self.tblw_Liste.verticalHeaderItem(9)
        item.setText(_translate("mw_Hukuk1", "10"))
        item = self.tblw_Liste.horizontalHeaderItem(0)
        item.setText(_translate("mw_Hukuk1", "1"))
        item = self.tblw_Liste.horizontalHeaderItem(1)
        item.setText(_translate("mw_Hukuk1", "2"))
        item = self.tblw_Liste.horizontalHeaderItem(2)
        item.setText(_translate("mw_Hukuk1", "3"))
        item = self.tblw_Liste.horizontalHeaderItem(3)
        item.setText(_translate("mw_Hukuk1", "4"))
        item = self.tblw_Liste.horizontalHeaderItem(4)
        item.setText(_translate("mw_Hukuk1", "5"))
        item = self.tblw_Liste.horizontalHeaderItem(5)
        item.setText(_translate("mw_Hukuk1", "6"))
        item = self.tblw_Liste.horizontalHeaderItem(6)
        item.setText(_translate("mw_Hukuk1", "7"))
        item = self.tblw_Liste.horizontalHeaderItem(7)
        item.setText(_translate("mw_Hukuk1", "8"))
        item = self.tblw_Liste.horizontalHeaderItem(8)
        item.setText(_translate("mw_Hukuk1", "9"))
        item = self.tblw_Liste.horizontalHeaderItem(9)
        item.setText(_translate("mw_Hukuk1", "10"))
        item = self.tblw_Liste.horizontalHeaderItem(10)
        item.setText(_translate("mw_Hukuk1", "11"))
        item = self.tblw_Liste.horizontalHeaderItem(11)
        item.setText(_translate("mw_Hukuk1", "12"))
        item = self.tblw_Liste.horizontalHeaderItem(12)
        item.setText(_translate("mw_Hukuk1", "13"))
        item = self.tblw_Liste.horizontalHeaderItem(13)
        item.setText(_translate("mw_Hukuk1", "14"))
        item = self.tblw_Liste.horizontalHeaderItem(14)
        item.setText(_translate("mw_Hukuk1", "15"))
        item = self.tblw_Liste.horizontalHeaderItem(15)
        item.setText(_translate("mw_Hukuk1", "16"))
        item = self.tblw_Liste.horizontalHeaderItem(16)
        item.setText(_translate("mw_Hukuk1", "17"))
        item = self.tblw_Liste.horizontalHeaderItem(17)
        item.setText(_translate("mw_Hukuk1", "18"))
        self.btn_KayitEkle.setText(_translate("mw_Hukuk1", "KAYIT EKLE"))
        self.btn_KayitGuncelle.setText(_translate("mw_Hukuk1", "KAYIT GÜNCELLE"))
        self.btn_KayitSil.setText(_translate("mw_Hukuk1", "KAYIT SİL"))
        self.grb_DavaciBilgileri.setTitle(_translate("mw_Hukuk1", "DAVACI BİLGİLERİ"))
        self.rbtn_Bekar.setText(_translate("mw_Hukuk1", "Bekar"))
        self.label_4.setText(_translate("mw_Hukuk1", "Müvekkil Cep No:"))
        self.lne_MuvekilCepNo.setInputMask(_translate("mw_Hukuk1", "999 999 99 99"))
        self.rbtn_Evli.setText(_translate("mw_Hukuk1", "Evli"))
        self.label_5.setText(_translate("mw_Hukuk1", "Müvekkil Adresi: "))
        self.label_11.setText(_translate("mw_Hukuk1", "Medeni durumu:"))
        self.label_3.setText(_translate("mw_Hukuk1", "Müvekkil TC No:"))
        self.cmb_ilce.setItemText(0, _translate("mw_Hukuk1", "Esenyurt"))
        self.cmb_ilce.setItemText(1, _translate("mw_Hukuk1", "Beylikdüzü"))
        self.cmb_ilce.setItemText(2, _translate("mw_Hukuk1", "Avcılar"))
        self.cmb_ilce.setItemText(3, _translate("mw_Hukuk1", "Şirinevler"))
        self.cmb_ilce.setItemText(4, _translate("mw_Hukuk1", "Kadıköy"))
        self.cmb_ilce.setItemText(5, _translate("mw_Hukuk1", "Eminönü"))
        self.cmb_ilce.setItemText(6, _translate("mw_Hukuk1", "Taksim"))
        self.cmb_ilce.setItemText(7, _translate("mw_Hukuk1", "Bahçelievler"))
        self.cmb_ilce.setItemText(8, _translate("mw_Hukuk1", "Büyükçekmece"))
        self.cmb_ilce.setItemText(9, _translate("mw_Hukuk1", "Silivri"))
        self.label_17.setText(_translate("mw_Hukuk1", "İlçe: "))
        self.label.setText(_translate("mw_Hukuk1", "Müvekkil Ad Soyad:"))
        self.label_13.setText(_translate("mw_Hukuk1", "Dava Avukatı:"))
        self.label_19.setText(_translate("mw_Hukuk1", "Ücret:"))
        self.grb_DavaliBilgileri.setTitle(_translate("mw_Hukuk1", "DAVALI BİLGİLERİ"))
        self.label_14.setText(_translate("mw_Hukuk1", "Karşı Avukat:"))
        self.label_12.setText(_translate("mw_Hukuk1", "Davalı Adresi:"))
        self.label_8.setText(_translate("mw_Hukuk1", "Davalı Ad Soyad:"))
        self.label_10.setText(_translate("mw_Hukuk1", "Davalı Cep No:"))
        self.lne_DavaliCepNo.setInputMask(_translate("mw_Hukuk1", "999 999 99 99"))
        self.grb_DavaBilgileri.setTitle(_translate("mw_Hukuk1", "DAVA BİLGİLERİ"))
        self.cmb_DurusmaSalonu.setItemText(0, _translate("mw_Hukuk1", "Salon 1"))
        self.cmb_DurusmaSalonu.setItemText(1, _translate("mw_Hukuk1", "Salon 2"))
        self.cmb_DurusmaSalonu.setItemText(2, _translate("mw_Hukuk1", "Salon 3"))
        self.cmb_DurusmaSalonu.setItemText(3, _translate("mw_Hukuk1", "Salon 4"))
        self.cmb_DurusmaSalonu.setItemText(4, _translate("mw_Hukuk1", "Salon 5"))
        self.cmb_DurusmaSalonu.setItemText(5, _translate("mw_Hukuk1", "Salon 6"))
        self.cmb_DurusmaSalonu.setItemText(6, _translate("mw_Hukuk1", "Salon 7"))
        self.cmb_MahkemeBinasi.setItemText(0, _translate("mw_Hukuk1", "Büyükçekmece Adliyesi"))
        self.cmb_MahkemeBinasi.setItemText(1, _translate("mw_Hukuk1", "Küçükçekmece Adliyesi"))
        self.cmb_MahkemeBinasi.setItemText(2, _translate("mw_Hukuk1", "Anadolu Adalet Sarayı"))
        self.cmb_MahkemeBinasi.setItemText(3, _translate("mw_Hukuk1", "Ceneviz Mahkeme Binası"))
        self.cmb_MahkemeBinasi.setItemText(4, _translate("mw_Hukuk1", "Bakırköy Adliyesi"))
        self.cmb_MahkemeBinasi.setItemText(5, _translate("mw_Hukuk1", "Silivri Adliyesi"))
        self.label_7.setText(_translate("mw_Hukuk1", "Uzlaşma:"))
        self.label_6.setText(_translate("mw_Hukuk1", "Dava Türü:"))
        self.rbtn_Yok.setText(_translate("mw_Hukuk1", "Yok"))
        self.rbtn_Var.setText(_translate("mw_Hukuk1", "Var"))
        self.cmb_DavaTuru.setItemText(0, _translate("mw_Hukuk1", "Hukuk"))
        self.cmb_DavaTuru.setItemText(1, _translate("mw_Hukuk1", "Ceza"))
        self.cmb_DavaTuru.setItemText(2, _translate("mw_Hukuk1", "İdari"))
        self.cmb_DavaTuru.setItemText(3, _translate("mw_Hukuk1", "İcra"))
        self.label_16.setText(_translate("mw_Hukuk1", "Mahkeme Binası:"))
        self.label_18.setText(_translate("mw_Hukuk1", "Duruşma Salonu:"))
        self.label_15.setText(_translate("mw_Hukuk1", "Duruşma Tarihi:"))
        self.btn_Listele.setText(_translate("mw_Hukuk1", "LİSTELE"))
        self.btn_KayitAra.setText(_translate("mw_Hukuk1", "KAYIT ARA"))
        self.btn_Cikis.setText(_translate("mw_Hukuk1", "ÇIKIŞ"))
        self.btn_hakkinda.setText(_translate("mw_Hukuk1", "Hakkında"))
        self.actionHakk_nda.setText(_translate("mw_Hukuk1", "Hakkında"))
